#!/usr/bin/env python3
"""Write the cost estimates, forms 2.20 and 2.21, into the tab "5: Cost Estimation" of the Doc.

The content is derived from docs/forms/2-20-cost-estimates.en.md, which tools/cost_estimate.py
generates; nothing is authored here. What the Doc needs and the repo file does not:

  - the repo file's references to itself and to other repo files become references to the Doc's own
    sections and to the team's costing script;
  - each printed page is laid out as the book prints it: the dark title bar, the Project Title and
    Date Prepared line under it, the grey label over each part of form 2.21, the column header, and
    "Page N of M" under the grid; the Field | Content header table of the Markdown is folded into the
    Project Title line;
  - the tab is landscape and each printed page starts on a new page.

Run with:
    python tools/gdoc_cost_tab.py --doc DOC_ID --dry-run
    python tools/gdoc_cost_tab.py --doc DOC_ID
    python tools/gdoc_cost_tab.py --doc DOC_ID --clear      # rewrite a tab written before
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import sys
import time

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import gdoc_edit as ge
import gdoc_form

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "forms" / "2-20-cost-estimates.en.md"
DEFAULT_DIR = os.path.expanduser("~/.config/qldapm")
TAB = "5: Cost Estimation"
TITLE = "Development and Deployment of a Learning Center Management Software"
PAGE = "@@PAGE {}@@"
SMALL = 8
# The two widest grids carry eleven and twelve columns of money; at 8pt a 13-digit amount breaks.
TINY = {"ACTIVITY COST ESTIMATES": 7, "BOTTOM-UP COST ESTIMATING WORKSHEET": 7}
PADDING = 2

REWRITES = [
    ("Every figure is generated by `tools/cost_estimate.py` from `scope-package.en.md`, the levelling "
     "of `tools/level.py`, and the prices it lists; change those and rerun it rather than editing this "
     "file.",
     "Every figure is generated by the team's costing script from the WBS dictionary of section 3.3, the "
     "levelled schedule of section 4.1, and the prices of section 5.6; it is regenerated from them rather "
     "than edited here."),
    ("the levelling of form 2.18 run on that reduced work", "the levelling of section 4.1 run on that "
     "reduced work"),
    ("the scope change request `3-3-change-request-scope.en.md` carries", "the scope change request carries"),
    ("The reduction goes to the sponsor in `3-3-change-request-scope.en.md`, because",
     "The reduction goes to the sponsor in the scope change request, because"),
    ("PMBOK6_and_Agile_Practice_Guide.pdf in the team repository",
     "PMBOK Guide and Agile Practice Guide, PDF"),
]

# (marker heading in the Markdown, section heading in the Doc, printed title, page footer)
PAGES = [
    ("#### ACTIVITY COST ESTIMATES, page 1 of 1", "### 5.2 Activity Cost Estimates",
     "ACTIVITY COST ESTIMATES", "Page 1 of 1"),
    ("#### COST ESTIMATING WORKSHEET, page 1 of 2", "### 5.3 Cost Estimating Worksheet",
     "COST ESTIMATING WORKSHEET", "Page 1 of 2"),
    ("#### BOTTOM-UP COST ESTIMATING WORKSHEET, page 2 of 2", "",
     "BOTTOM-UP COST ESTIMATING WORKSHEET", "Page 2 of 2"),
]
PARTS = ["Parametric Estimates", "Analogous Estimates", "Three-Point Estimates"]

# Points, for a landscape page with the Doc's margins, about 648pt of usable width.
WIDTHS = {
    "Field": [130, 518],
    "Person": [120, 176, 176, 176],
    "Work package": [250, 80, 70, 50, 198],
    "Charter budget line": [280, 120, 120, 120],
    "Step": [400, 120, 128],
    "Item": [200, 100, 348],
}
FORM_WIDTHS = {
    "ACTIVITY COST ESTIMATES": [50, 76, 58, 52, 46, 58, 44, 78, 88, 54, 42],
    "Parametric Estimates": [80, 250, 100, 90, 120],
    "Analogous Estimates": [80, 140, 90, 140, 70, 120],
    "Three-Point Estimates": [170, 90, 90, 90, 100, 100],
    "BOTTOM-UP COST ESTIMATING WORKSHEET": [118, 34, 42, 62, 38, 46, 48, 42, 52, 52, 46, 62],
}


def build() -> str:
    md = SOURCE.read_text(encoding="utf-8")
    date = re.search(r"^\*\*Date prepared:\*\* (.+)$", md, re.M).group(1).strip()
    body = md[md.index("\n\n", md.index("**Source:**")):].strip("\n")
    for old, new in REWRITES:
        if old not in body:
            raise SystemExit("expected text not found, the source has changed: %r" % old[:60])
        body = body.replace(old, new)

    m = re.search(r"^\*Reading convention\. (.*?)\*\n", body, re.S | re.M)
    body = body[:m.start()] + "#### Reading convention\n\n" + m.group(1) + "\n" + body[m.end():]
    body = body.replace("### Rules of the estimate", "### 5.1 Rules of the estimate")

    header = ("| Field | Content |\n| --- | --- |\n| **Project Title** | %s |\n| **Date Prepared** | %s |\n\n"
              % (TITLE, date))
    if body.count(header) != 3:
        raise SystemExit("expected one Project Title box per printed page")
    body = body.replace(header, "")

    for n, (marker, heading, _title, footer) in enumerate(PAGES):
        nxt = PAGES[n + 1][0] if n + 1 < len(PAGES) else "\n---\n"
        start = body.index(marker)
        end = body.index(nxt, start)
        page = body[start:end].replace(marker + "\n", (heading + "\n") if heading else "")
        page = page.rstrip() + "\n\n" + PAGE.format(footer) + "\n\n"
        body = body[:start] + page + body[end:]
    for part in PARTS:
        body = body.replace("**%s**\n\n" % part, "")

    body = body.replace("\n---\n", "\n")
    body = body.replace("### Paid time without booked work", "### 5.4 Paid time without booked work")
    body = body.replace("### Estimate against the charter: for the team to decide",
                        "### 5.5 Estimate against the charter: for the team to decide")
    body = body.replace("### References", "### 5.6 References")
    if "`" in body:
        raise SystemExit("a repo reference in backticks is left in the tab text")
    return "## %s\n\n%s\n" % (TAB, body.strip())


def units(text: str):
    """Cut before each section heading, so one write stays a moderate size."""
    cuts = [0] + [m.start() for m in re.finditer(r"^### 5\.\d ", text, re.M)]
    # The bottom-up page is a table of some 800 cells; it goes out on its own.
    cuts.append(text.index(PAGE.format("Page 1 of 2")) + len(PAGE.format("Page 1 of 2")))
    cuts = sorted(set(cuts))
    return [text[a:b] for a, b in zip(cuts, cuts[1:] + [len(text)])]


# ------------------------------------------------------------------ writing

CHUNK = 400


class Doc(ge.Doc):
    """ge.Doc whose table fill goes out in chunks: the bottom-up worksheet is some 850 cells, one
    request too large for the API to answer in time. The fill runs from the last cell to the first,
    so each chunk leaves the indexes of the next valid without a read in between."""

    def _materialise_table(self, tab_n, placeholder, table_block):
        """As ge.Doc does it, with the placeholder removal and the fill sent in chunks."""
        tab_id, content = self.tab(tab_n)
        ph = ge.find_para(content, lambda t: t == placeholder)
        rows = table_block["rows"]
        before_len = content[-1]["endIndex"]
        self.batch([{"insertTable": {"rows": len(rows), "columns": max(len(r) for r in rows),
                                     "location": {"index": ph["startIndex"], "tabId": tab_id}}}])
        tab_id, content = self.tab(tab_n)
        ph = ge.find_para(content, lambda t: t == placeholder)
        table_el = next(el for el in reversed(ge.top_tables(content)) if el["endIndex"] <= ph["startIndex"])
        reqs = [{"deleteContentRange": {"range": {"startIndex": ph["startIndex"],
                                                  "endIndex": ph["endIndex"], "tabId": tab_id}}}]
        reqs += self.fill_table(tab_id, table_el, rows, table_block["header"])
        for k in range(0, len(reqs), CHUNK):
            self.svc.documents().batchUpdate(documentId=self.id,
                                             body={"requests": reqs[k:k + CHUNK]}).execute()
            self.calls += 1
        self.refresh()
        return self.content(tab_n)[-1]["endIndex"] - before_len


def docs_service(creds):
    import google_auth_httplib2
    import httplib2
    from googleapiclient.discovery import build as discovery_build
    http = google_auth_httplib2.AuthorizedHttp(creds, http=httplib2.Http(timeout=600))
    return discovery_build("docs", "v1", http=http, cache_discovery=False)


# ------------------------------------------------------------------ layout

def _table(doc, tab_n, start_index):
    tab_id, content = doc.tab(tab_n)
    return tab_id, next(el for el in ge.top_tables(content) if el["startIndex"] == start_index)


def full_row(doc, tab_n, start_index, row, text, background=None, center=False):
    """Insert a row above `row`, write `text` in its first cell, and merge it across the table."""
    tab_id, table_el = _table(doc, tab_n, start_index)
    doc.batch([gdoc_form.insert_row_above(tab_id, table_el, row)])
    tab_id, table_el = _table(doc, tab_n, start_index)
    doc.batch(doc.set_cell(tab_id, ge.table_cells(table_el)[row][0], text))
    tab_id, table_el = _table(doc, tab_n, start_index)
    ncols = len(ge.table_cells(table_el)[-1])
    reqs = [gdoc_form.merge(tab_id, table_el, row, 0, 1, ncols)]
    if background:
        reqs.append(gdoc_form.style(tab_id, table_el, row, 0, 1, 1, background=background))
    doc.batch(reqs)
    if center:
        tab_id, table_el = _table(doc, tab_n, start_index)
        s, e = ge.cell_range(ge.table_cells(table_el)[row][0])
        doc.batch([{"updateParagraphStyle": {"range": {"startIndex": s, "endIndex": e, "tabId": tab_id},
                                             "paragraphStyle": {"alignment": "CENTER"},
                                             "fields": "alignment"}}])


def small_text(doc, tab_n, start_index, header_rows, size=SMALL):
    """The printed forms set their grids in a small face with tight cells; the header rows are bold."""
    tab_id, table_el = _table(doc, tab_n, start_index)
    rows = ge.table_cells(table_el)
    pad = {"magnitude": PADDING, "unit": "PT"}
    reqs = [{"updateTextStyle": {
        "range": {"startIndex": table_el["startIndex"], "endIndex": table_el["endIndex"], "tabId": tab_id},
        "textStyle": {"fontSize": {"magnitude": size, "unit": "PT"}}, "fields": "fontSize"}},
        {"updateTableCellStyle": {
            "tableRange": {"tableCellLocation": {"tableStartLocation": {"index": table_el["startIndex"],
                                                                        "tabId": tab_id},
                                                 "rowIndex": 0, "columnIndex": 0},
                           "rowSpan": len(rows), "columnSpan": max(len(r) for r in rows)},
            "tableCellStyle": {"paddingLeft": pad, "paddingRight": pad},
            "fields": "paddingLeft,paddingRight"}}]
    for row in ge.table_cells(table_el)[:header_rows]:
        for cell in row:
            s, e = ge.cell_range(cell)
            if e > s:
                reqs.append({"updateTextStyle": {"range": {"startIndex": s, "endIndex": e, "tabId": tab_id},
                                                 "textStyle": {"bold": True}, "fields": "bold"}})
    doc.batch(reqs)


def tables_between(doc, tab_n, start_marker, end_marker):
    tab_id, content = doc.tab(tab_n)
    a = ge.find_para(content, lambda t: t.strip() == start_marker)
    b = ge.find_para(content, lambda t: t.strip() == end_marker)
    return [el["startIndex"] for el in ge.top_tables(content)
            if a["startIndex"] < el["startIndex"] < b["startIndex"]]


def lay_out_page(doc, tab_n, title, footer, date, after):
    """Title bar, Project Title line, part labels, small face, and the footer, as the book prints."""
    starts = tables_between(doc, tab_n, after, PAGE.format(footer))
    project = "**Project Title:** %s          **Date Prepared:** %s" % (TITLE, date)
    if title == "COST ESTIMATING WORKSHEET":
        # One frame, three parts: the title and project line over the first part only.
        for start, part in reversed(list(zip(starts, PARTS))):
            full_row(doc, tab_n, start, 0, "**%s**" % part, background=gdoc_form.GREY)
            tab_id, table_el = _table(doc, tab_n, start)
            doc.batch(gdoc_form.column_widths(tab_id, table_el, FORM_WIDTHS[part]))
            small_text(doc, tab_n, start, 2)
        first = starts[0]
        full_row(doc, tab_n, first, 0, project)
        full_row(doc, tab_n, first, 0, "**%s**" % title, background=gdoc_form.DARK, center=True)
        whiten_title(doc, tab_n, first)
    else:
        start = starts[0]
        tab_id, table_el = _table(doc, tab_n, start)
        doc.batch(gdoc_form.column_widths(tab_id, table_el, FORM_WIDTHS[title]))
        small_text(doc, tab_n, start, 1, TINY.get(title, SMALL))
        full_row(doc, tab_n, start, 0, project)
        full_row(doc, tab_n, start, 0, "**%s**" % title, background=gdoc_form.DARK, center=True)
        whiten_title(doc, tab_n, start)
    footer_line(doc, tab_n, footer)


def whiten_title(doc, tab_n, start):
    tab_id, table_el = _table(doc, tab_n, start)
    s, e = ge.cell_range(ge.table_cells(table_el)[0][0])
    doc.batch([{"updateTextStyle": {"range": {"startIndex": s, "endIndex": e, "tabId": tab_id},
                                    "textStyle": {"foregroundColor": gdoc_form.WHITE, "bold": True,
                                                  "fontSize": {"magnitude": 14, "unit": "PT"}},
                                    "fields": "foregroundColor,bold,fontSize"}}])


def footer_line(doc, tab_n, footer):
    tab_id, content = doc.tab(tab_n)
    el = ge.find_para(content, lambda t: t.strip() == PAGE.format(footer))
    s = el["startIndex"]
    doc.batch([{"deleteContentRange": {"range": {"startIndex": s, "endIndex": el["endIndex"] - 1,
                                                 "tabId": tab_id}}},
               {"insertText": {"location": {"index": s, "tabId": tab_id}, "text": footer}},
               {"updateParagraphStyle": {"range": {"startIndex": s, "endIndex": s + len(footer) + 1,
                                                   "tabId": tab_id},
                                         "paragraphStyle": {"alignment": "CENTER", "namedStyleType": "NORMAL_TEXT"},
                                         "fields": "alignment,namedStyleType"}}])


def other_tables(doc, tab_n):
    """Column widths and the small face for the tables outside the printed forms."""
    tab_id, content = doc.tab(tab_n)
    for el in ge.top_tables(content):
        first = ge.cell_text(ge.table_cells(el)[0][0]).strip()
        if first in WIDTHS:
            doc.batch(gdoc_form.column_widths(tab_id, el, WIDTHS[first]))
            small_text(doc, tab_n, el["startIndex"], 1)
            tab_id, content = doc.tab(tab_n)


def page_breaks(doc, tab_n):
    """Each section from 5.2 opens a page; page 2 of form 2.21 gets a hard break after page 1."""
    tab_id, content = doc.tab(tab_n)
    reqs = []
    for el in ge.top_paragraphs(content):
        if re.match(r"^5\.[2-6] ", ge.para_text(el).strip()):
            reqs.append({"updateParagraphStyle": {
                "range": {"startIndex": el["startIndex"], "endIndex": el["endIndex"], "tabId": tab_id},
                "paragraphStyle": {"pageBreakBefore": True}, "fields": "pageBreakBefore"}})
    doc.batch(reqs)
    tab_id, content = doc.tab(tab_n)
    el = ge.find_para(content, lambda t: t.strip() == "Page 1 of 2")
    doc.batch([{"insertPageBreak": {"location": {"index": el["endIndex"] - 1, "tabId": tab_id}}}])


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--doc", required=True)
    p.add_argument("--tab", default=TAB)
    p.add_argument("--token", default=os.path.join(DEFAULT_DIR, "token.json"))
    p.add_argument("--clear", action="store_true",
                   help="empty this tab first; only this tab is touched")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--preview", default="", help="write the tab text to this file and stop")
    a = p.parse_args(argv)

    text = build()
    parts = units(text)
    tables = sum(1 for u in parts for b in ge.parse_blocks(u) if b["type"] == "table")
    print("payload: %d characters, %d units, %d tables" % (len(text), len(parts), tables))
    if a.preview:
        pathlib.Path(a.preview).write_text(text, encoding="utf-8")
        print("preview written to %s" % a.preview)
        return 0
    if a.dry_run:
        for u in parts:
            print("  unit %6d chars  %s" % (len(u), u.splitlines()[0][:70]))
        return 0

    import gdoc

    creds = gdoc.load_creds(pathlib.Path(a.token))
    doc = Doc(docs_service(creds), a.doc)
    names = [t[0].strip() for t in doc.tabs()]
    if a.tab not in names:
        raise SystemExit("no tab %r in this Doc; tabs present: %s" % (a.tab, names))
    tab_n = names.index(a.tab)
    tab_id, content = doc.tab(tab_n)
    if a.clear and content[-1]["endIndex"] > 2:
        doc.delete_range(tab_id, 1, content[-1]["endIndex"] - 1)
        tab_id, content = doc.tab(tab_n)
    if content[-1]["endIndex"] > 2:
        raise SystemExit("tab %r is not empty; run with --clear to rewrite it" % a.tab)
    doc.batch([{"updateDocumentStyle": {"tabId": tab_id,
                                        "documentStyle": {"flipPageOrientation": True},
                                        "fields": "flipPageOrientation"}}])
    for k, u in enumerate(parts, 1):
        doc.insert_markdown(tab_n, doc.content(tab_n)[-1]["endIndex"] - 1, u)
        print("  wrote unit %d of %d (%d API calls)" % (k, len(parts), doc.calls))
        time.sleep(0.5)

    date = re.search(r"^\*\*Date prepared:\*\* (.+)$", SOURCE.read_text(encoding="utf-8"), re.M).group(1)
    after = ["5.2 Activity Cost Estimates", "5.3 Cost Estimating Worksheet", "Page 1 of 2"]
    for (_marker, _heading, title, footer), start in zip(PAGES, after):
        lay_out_page(doc, tab_n, title, footer, date.strip(), start)
        print("  laid out %s, %s" % (title, footer))
    other_tables(doc, tab_n)
    page_breaks(doc, tab_n)
    print("done, %d API calls" % doc.calls)
    return 0


if __name__ == "__main__":
    sys.exit(main())
