#!/usr/bin/env python3
"""Write the project schedule, form 2.18, and its change request, form 3.3, into a tab of the Doc.

The content is derived from docs/forms/2-18-project-schedule.en.md and
docs/forms/3-3-change-request.en.md; nothing is authored here. What the Doc needs and the repo files
do not:

  - references to repo files become references to the Doc's own sections;
  - the Mermaid blocks are dropped, since the charts come as images;
  - form 3.3's check boxes become one line of boxes per printed group, as the form prints them;
  - the tab is landscape, and each printed page starts on a new page.

Images: the Docs API inserts an image only from a URL it can fetch, so each chart is uploaded to the
user's Drive, readable by link for the moment of insertion, and deleted once the Doc holds its own
copy.

Run with:
    python3 tools/gdoc_schedule_tab.py --doc DOC_ID --dry-run
    python3 tools/gdoc_schedule_tab.py --doc DOC_ID --create
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import sys
import time

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import gdoc_edit as ge

ROOT = pathlib.Path(__file__).resolve().parent.parent
FORMS = ROOT / "docs" / "forms"
ASSETS = ROOT / "docs" / "assets"
SCHEDULE = FORMS / "2-18-project-schedule.en.md"
CHANGE = FORMS / "3-3-change-request.en.md"
DEFAULT_DIR = os.path.expanduser("~/.config/qldapm")
TAB = "4: Project Schedule"
IMAGE = "@@IMAGE {}@@"
# Usable area of a landscape Letter page with the Doc's one-inch margins, in points.
MAX_W, MAX_H = 648, 468
BOX, TICKED = "☐", "☒"

REWRITES = [
    ("the WBS dictionary in `scope-package.en.md`", "the WBS dictionary in section 3.3"),
    ("change request `3-3-change-request.en.md`", "the change request of section 4.2"),
    ("The form is generated by `tools/schedule.py`;\nchange the source documents and rerun it rather "
     "than editing this file.",
     "The form is generated from sections 2 and 3 by the team's scheduling script, and is\n"
     "regenerated from them rather than edited here."),
    ("form 2.18, `2-18-project-schedule.en.md`,", "form 2.18 in section 4.1,"),
    ("The figures come from\n`tools/level.py` run on 29 September 2026 against the scope package and "
     "the charter as they stand.",
     "The figures come from\nthe levelling run of 29 September 2026 against sections 2 and 3 as they "
     "stand."),
    ("Check\nboxes are marked `[x]` where they apply.",
     "A ticked\nbox, %s, marks what applies." % TICKED),
]


def body_of(md: str) -> tuple[str, str]:
    """(date prepared, body) with the H1 and the three bold header lines removed."""
    date = re.search(r"^\*\*Date prepared:\*\* (.+)$", md, re.M).group(1).strip()
    lines = md.splitlines()
    start = next(i for i, l in enumerate(lines) if l.startswith("*Reading convention"))
    return date, "\n".join(lines[start:])


def reading_note(body: str) -> str:
    """The italic reading convention becomes a headed paragraph, as in section 3."""
    m = re.match(r"^\*Reading convention\. (.*?)\*\n", body, re.S)
    text = m.group(1)
    return "#### Reading convention\n\n" + text + "\n" + body[m.end():]


def checkboxes(body: str) -> str:
    """Each run of '- [ ]' items becomes one paragraph of boxes."""
    out, run = [], []

    def flush():
        if run:
            out.append("    ".join(run))
            run.clear()

    for line in body.splitlines():
        m = re.match(r"^- \[([ x])\] (.+)$", line.strip())
        if m:
            run.append("%s %s" % (TICKED if m.group(1) == "x" else BOX, m.group(2)))
            continue
        flush()
        out.append(line)
    flush()
    return "\n".join(out)


def build() -> str:
    date, sched = body_of(SCHEDULE.read_text(encoding="utf-8"))
    _, change = body_of(CHANGE.read_text(encoding="utf-8"))
    text = "\n".join([
        "## %s" % TAB,
        "",
        "**Project Title:** Development and Deployment of a Learning Center Management Software",
        "",
        "**Date Prepared:** %s" % date,
        "",
        "The schedule of PMBOK 6 section 6.5 Develop Schedule, reproduced from form 2.18 of A Project "
        "Manager's Book of Forms, 3rd edition, and the change request, form 3.3, that carries its dates "
        "to the sponsor. It is levelled from the work packages of section 3 and the milestones of "
        "section 2.",
        "",
        "### 4.1 Project Schedule",
        "",
        reading_note(sched),
        "",
        "### 4.2 Change Request",
        "",
        reading_note(checkboxes(change)),
    ])
    for old, new in REWRITES:
        if old not in text:
            raise SystemExit("expected text not found, the source has changed: %r" % old[:60])
        text = text.replace(old, new)
    text = re.sub(r"```mermaid\n.*?```\n?", "", text, flags=re.S)
    text = re.sub(r"^!\[[^\]]*\]\(\.\./assets/([^)]+)\)$", lambda m: IMAGE.format(m.group(1)), text,
                  flags=re.M)
    text = text.replace("### Resource loading after levelling", "#### Resource loading after levelling")
    text = re.sub(r"\n---\n", "\n", text)
    # The form prints labelled boxes, not a Field | Content grid; the labels are bold already.
    text = text.replace("| Field | Content |\n| --- | --- |\n", "")
    if "`" in text:
        raise SystemExit("a repo reference in backticks is left in the tab text")
    return text.rstrip() + "\n"


def units(text: str):
    """Cut before each page marker and section heading, so one write stays a moderate size."""
    cuts = [0] + [m.start() for m in re.finditer(r"^#{3,4} (4\.2 |PROJECT SCHEDULE|CHANGE REQUEST|"
                                                  r"Resource loading)", text, re.M)]
    return [text[a:b] for a, b in zip(cuts, cuts[1:] + [len(text)])]


# ------------------------------------------------------------------ writing

CHUNK = 400


class Doc(ge.Doc):
    """ge.Doc whose table fill goes out in chunks: the Gantt table alone is some 2,000 cells, one
    request too large for the API to answer in time. The fill runs from the last cell to the first,
    so each chunk leaves the indexes of the next valid without a read in between."""

    def _materialise_table(self, tab_n, placeholder, table_block):
        tab_id, content = self.tab(tab_n)
        ph = ge.find_para(content, lambda t: t == placeholder)
        rows = table_block["rows"]
        before_len = content[-1]["endIndex"]
        self.batch([{"deleteContentRange": {"range": {"startIndex": ph["startIndex"],
                                                      "endIndex": ph["endIndex"] - 1, "tabId": tab_id}}},
                    {"insertTable": {"rows": len(rows), "columns": max(len(r) for r in rows),
                                     "location": {"index": ph["startIndex"], "tabId": tab_id}}}])
        tab_id, content = self.tab(tab_n)
        table_el = next(el for el in ge.top_tables(content) if el["startIndex"] >= ph["startIndex"])
        reqs = self.fill_table(tab_id, table_el, rows, table_block["header"])
        for k in range(0, len(reqs), CHUNK):
            self.svc.documents().batchUpdate(documentId=self.id,
                                             body={"requests": reqs[k:k + CHUNK]}).execute()
            self.calls += 1
        self.refresh()
        return self.content(tab_n)[-1]["endIndex"] - before_len


def docs_service(creds):
    import google_auth_httplib2
    import httplib2
    from googleapiclient.discovery import build
    http = google_auth_httplib2.AuthorizedHttp(creds, http=httplib2.Http(timeout=600))
    return build("docs", "v1", http=http, cache_discovery=False)


def image_size(path: pathlib.Path):
    import struct
    with open(path, "rb") as f:
        head = f.read(24)
    w, h = struct.unpack(">II", head[16:24])
    scale = min(MAX_W / w, MAX_H / h)
    return round(w * scale), round(h * scale)


def upload(drive, path: pathlib.Path):
    from googleapiclient.http import MediaFileUpload
    f = drive.files().create(body={"name": path.name}, media_body=MediaFileUpload(str(path),
                             mimetype="image/png"), fields="id").execute()
    drive.permissions().create(fileId=f["id"], body={"type": "anyone", "role": "reader"}).execute()
    return f["id"]


def place_images(doc, drive, tab_n):
    tab_id, content = doc.tab(tab_n)
    placeholders = [(el, re.match(r"^@@IMAGE (.+)@@$", ge.para_text(el).strip()))
                    for el in content if "paragraph" in el]
    placeholders = [(el, m.group(1)) for el, m in placeholders if m]
    uploaded = []
    try:
        # From the last to the first, so earlier indexes stay valid.
        for el, name in reversed(placeholders):
            path = ASSETS / name
            file_id = upload(drive, path)
            uploaded.append(file_id)
            w, h = image_size(path)
            start = el["startIndex"]
            doc.batch([
                {"deleteContentRange": {"range": {"startIndex": start,
                                                  "endIndex": el["endIndex"] - 1, "tabId": tab_id}}},
                {"insertInlineImage": {"location": {"index": start, "tabId": tab_id},
                                       "uri": "https://drive.google.com/uc?export=download&id=%s" % file_id,
                                       "objectSize": {"width": {"magnitude": w, "unit": "PT"},
                                                      "height": {"magnitude": h, "unit": "PT"}}}},
                {"updateParagraphStyle": {"range": {"startIndex": start, "endIndex": start + 1,
                                                    "tabId": tab_id},
                                          "paragraphStyle": {"alignment": "CENTER"},
                                          "fields": "alignment"}}])
            tab_id, content = doc.tab(tab_n)
            print("  image %s placed at %dx%d pt" % (name, w, h))
    finally:
        for file_id in uploaded:
            drive.files().delete(fileId=file_id).execute()
        print("  removed %d temporary Drive files" % len(uploaded))


def page_breaks(doc, tab_n):
    tab_id, content = doc.tab(tab_n)
    reqs = []
    for el in content:
        if "paragraph" not in el:
            continue
        t = ge.para_text(el).strip()
        if re.match(r"^(PROJECT SCHEDULE, page|CHANGE REQUEST, page|4\.2 |Resource loading)", t):
            reqs.append({"updateParagraphStyle": {
                "range": {"startIndex": el["startIndex"], "endIndex": el["endIndex"], "tabId": tab_id},
                "paragraphStyle": {"pageBreakBefore": True}, "fields": "pageBreakBefore"}})
    doc.batch(reqs)


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--doc", required=True)
    p.add_argument("--tab", default=TAB)
    p.add_argument("--token", default=os.path.join(DEFAULT_DIR, "token.json"))
    p.add_argument("--create", action="store_true", help="add the tab when it is missing")
    p.add_argument("--clear", action="store_true",
                   help="empty this tab first; it carries no comment threads of its own")
    p.add_argument("--dry-run", action="store_true")
    a = p.parse_args(argv)

    text = build()
    parts = units(text)
    tables = sum(1 for u in parts for b in ge.parse_blocks(u) if b["type"] == "table")
    print("payload: %d characters, %d units, %d tables, %d images"
          % (len(text), len(parts), tables, text.count("@@IMAGE")))
    if a.dry_run:
        for u in parts:
            print("  unit %5d chars  %s" % (len(u), u.splitlines()[0][:70]))
        return 0

    import gdoc

    creds = gdoc.load_creds(pathlib.Path(a.token))
    doc = Doc(docs_service(creds), a.doc)
    names = [t[0].strip() for t in doc.tabs()]
    if a.tab not in names:
        if not a.create:
            raise SystemExit("no tab %r; run with --create" % a.tab)
        doc.batch([{"addDocumentTab": {"tabProperties": {"title": a.tab}}}])
        names = [t[0].strip() for t in doc.tabs()]
        print("  created tab %r" % a.tab)
    tab_n = names.index(a.tab)
    tab_id, content = doc.tab(tab_n)
    if a.clear and content[-1]["endIndex"] > 2:
        doc.delete_range(tab_id, 1, content[-1]["endIndex"] - 1)
        tab_id, content = doc.tab(tab_n)
    if content[-1]["endIndex"] > 2:
        raise SystemExit("tab %r is not empty; it is written once, into an empty tab" % a.tab)
    doc.batch([{"updateDocumentStyle": {"tabId": tab_id,
                                        "documentStyle": {"flipPageOrientation": True},
                                        "fields": "flipPageOrientation"}}])
    for k, u in enumerate(parts, 1):
        doc.insert_markdown(tab_n, doc.content(tab_n)[-1]["endIndex"] - 1, u)
        print("  wrote unit %d of %d (%d API calls)" % (k, len(parts), doc.calls))
        time.sleep(0.5)
    page_breaks(doc, tab_n)
    place_images(doc, gdoc.drive(creds), tab_n)
    print("done, %d API calls" % doc.calls)
    return 0


if __name__ == "__main__":
    sys.exit(main())
